mod 'puppet-nginx', '3.2.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs/docker'
mod 'puppetlabs-java', '7.0.2'
mod 'puppet-archive', '5.0.0'
